//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $rootnamespace$
{
    
    internal partial class $safeitemname$
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (($safeitemname$.manager == null))
                {
                    $safeitemname$.manager = new System.Resources.ResourceManager("$rootnamespace$.$safeitemname$", typeof($safeitemname$).Assembly);
                }
                return $safeitemname$.manager;
            }
        }
    }
}
